language: node_js
node_js:
- '14'
sudo: required
dist: trusty
cache:
  npm: true
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
install:
- npm run install:mav
script: skip
jobs:
  include:
  - stage: test
    name: Run Tests
    if: branch != develop
    script:
    - cd packages/client-mav
    - npm run lint
    - npm run build:libs
  - stage: deploy
    name: Deploy demo to GitHub Pages
    if: branch = master
    script:
    - npm run build:mav-demo
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: false
      local-dir: packages/client-mav/dist/client-mav
      on:
        branch: master
  - stage: deploy
    name: Deploy staging to Netlify
    if: branch = develop
    script:
    - npm run build:staging
    deploy:
      provider: pages
      target-branch: staging
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: false
      local-dir: packages/client-mav/dist/client-mav
      on:
        branch: develop
notifications:
  slack:
    secure: gCju5wv7eoPmwiH494LNgn0rZdLdpcKsitJbSkehhE6tqFcfmy0I9AIWUZbwV022R5OiNgTL/cykssnF7HuBbiLEXmjWTQ5tBmH+ddDuKLlyUO+ElTdH5m12G2yK9KYqCjoFhlIPh0nXpTy1k4gpSyOwZnaeLAI1EFfSOFNGV44YQSGq+ag/OzcyeytYakLmg8tDbsCn0t7DMvKRVKnBGdKG7LsVYho26rm/FA7BeQRjx2/YtsEQlhtRXx3uW1mHD3Iwc+EvgtKMJgofq3NNBEYNSEsnA+E3ASECHe/Gk9NuHdJ/9fF1fVhrwTX8Sya1xhI7LdYAFjFhYynWfrPfgBH4Rkl8Z9HKI+taYvjeMYgO/leotmQ9/9OcGicqwYSPSFuMP6hFUgUCxLg97fhLExDjDtayBCEbjcUAbUX6T5Ukn9nIC5fsQGdDKRyUHfcs4cZD04qLoCo7PTKNyLL9FCECmVEsRdYpF8oW108IadhNiUCI8mB6NDYMyX6iZgCfX36XMwNf7FcjVrycYDoIonmtQ0m0bMQJhw+nrNyyGuWCfm1Caj8c7SlXJPyUIpWvKAcUaR6neHlN+cnQCmYJCK4CS87tfc5/kOWuKYeOeuya4Pc7yJvzyI72gMhTl+tfOEr8hYzX8cANIBYpqZ8rY7NUL4XCkB9eF9yBvgMpw30=
